// Generated by https://quicktype.io

export interface ItemDescription {
  author: Author;
  category: string[];
  items: Items;
}

export interface Author {
  name: string;
  lastName: string;
}

export interface Items {
  id: string;
  category_id: string;
  title: string;
  price: Price;
  picture: string;
  condition: string;
  free_shipping: boolean;
  sold_quantity: number;
  description: string;
}

export interface Price {
  currency: string;
  amount: number;
  decimals: null;
}
