// Generated by https://quicktype.io

export interface Items {
  author: Author;
  categories: string[];
  items: Item[];
}

export interface Author {
  name: string;
  lastName: string;
}

export interface Item {
  id: string;
  title: string;
  price: Price;
  picture: string;
  condition: string;
  free_shipping: boolean;
  address: string;
}

export interface Price {
  currency: string;
  amount: number;
  decimals: number | null;
}
